version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: cinemesh-postgres
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=cinemesh
      - POSTGRES_PASSWORD=cinemesh123!@#
      - POSTGRES_DB=cinemesh_default_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-init/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
    networks:
      - cinemesh-net

volumes:
  postgres_data:

networks:
  cinemesh-net:
    driver: bridge
