version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: cinemesh-postgres
    command: ["postgres", "-c", "wal_level=logical"]
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=cinemesh
      - POSTGRES_PASSWORD=cinemesh123!@#
      - POSTGRES_DB=cinemesh_default_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-init/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
    networks:
      - cinemesh-net

  kafka-connect:
    image: debezium/connect:2.5
    container_name: cinemesh-connect
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks:
      - cinemesh-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: cinemesh-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - cinemesh-net

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: cinemesh-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Listeners for Docker internal (29092) and Host machine (9092)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - cinemesh-net

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: cinemesh-kafka-ui
    ports:
      - "8090:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: cinemesh-connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
    networks:
      - cinemesh-net
volumes:
  postgres_data:

networks:
  cinemesh-net:
    driver: bridge
