application:
  security:
    accessToken:
      secretKey: e3f0acd51fe8f38b145c82074ac46abf3395db7ad3eb1a96166d31c35409b14fe7725d18bd177d860caaceb17decdc5a704c0ecc91a8e40ac4b5168e9a0af10e
      tokenValidityMilliseconds: 900000
    refreshToken:
      secretKey: e3f0acd51fe8f38b145c82074ac46abf3395db7ad3eb1a96166d31c35409b14fe7725d18bd177d860caaceb17decdc5a704c0ecc91a8e40ac4b5168e9a0af10e
      tokenValidityMilliseconds: 1800000

feign:
  domain:
    movie-service: localhost:9002
    theater-service: localhost:9003
    auth-service: localhost:9000
